Repository AY2223S1-CS2103T-T09-4/tp, pull requests merged in 2022-10, with the labels that each got.

#79 Add ability to get ID of student in list
  src/main/java/seedu/address/logic/commands/GetIdCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GetIdCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/GetIdCommandTest.java
  src/test/java/seedu/address/logic/parser/GetIdCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.HIGH, type.Task, type.task.getID

#109 Add in ability to detect class conflict
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/ClassStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonSerializableAddressBookTest/personsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/ClassStorageTest.java
Labels: priority.HIGH, type.Task, type.Task.Update

#129 Fix `clear` command bug where schedule was not updated when command ran
  src/main/java/seedu/address/model/person/UniqueScheduleList.java
Labels: bug

#127 Free up time slot after deleting a student and using clear command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/ClassStorage.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/storage/ClassStorageTest.java
Labels: bug

#153 Enable assertions when executing Java code
  build.gradle
Labels: enhancement

#200 Add Sort and Undo command to UG
  docs/UserGuide.md
Labels: documentation

#221 Update UG with sequence of commands and add missing rates per class field
  docs/UserGuide.md
  docs/images/UG-screenshots/UiList.png
Labels: documentation

#225 Add missed description for UG sorting
  docs/UserGuide.md
Labels: documentation

#290 Update UG based on bugs reported
  docs/UserGuide.md
Labels: documentation
